language: node_js
script:
- make test
before_deploy:
- make archive
cache: yarn
deploy:
  provider: releases
  api_key:
    secure: BW2krqyU/WjLdPHe9F839JReDAaz5N2eNFP680Hy+fJmlHfPiLoxNuEulpXfZEc+MSxEP9TzWgWoY7bEdkjvbTexNzIEeRpxojcMuH4e8Yf50tSB62qz8it48afowT6wCVQcg3cC9ahBeQZ57u3NchpxCAte4JtPu+BE89VI+B5kYohuJ7KX7i1bseJyuHBCZaWYb1EmOpoICIW1/LtHoDeqnxK/ipa/kRT/05bcmi/LjAsirQjbbRJ791Tz3kjPaIsnNRstjxKIEHuu+qGOgIgMHzwWeYz39er6NouGSlZaZySj7lGuY/TUTvdlLEbL2L5sIteT6Wz8pf2UmB7OhbcLzj2LPZ2VrVhw2Xk//qrQnuwrKiiOGHrWThB+1UpWLp2fu9i/w9WXrsk4zfuHKf7nZItllwYFhiDhBIKdUHkbaYlrCanTIUWCvHsWjlOZyqD7Xi+vfUUjLRq6ZxJpUDx2tt/JFNRPhQA8eO68NHw3ojO+5QA/izVfoFe2MUpEW/5ICPCJzRkISc8HmAvGi3mDVK6lZsGn1ReXwRmdBnR+5RDh65GM9+CcwD0nzkK00/lrxdXlVtsqhs+J0lAb+zhKiSfJTzLYfHDoZ4qwA734joixaCA9pbmc5JHjZ+/3hNiRnhu7t8DIfva9kV++CwYAXOk2TKrrwa/1os6OUCY=
  file: dist/cURLImporter.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-cURLImporter
